kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "echo-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/geek182/openshift.git"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: bc/Jenkinsfile

