pipeline { 
      agent  any 
      stages {
        stage('preamble') {
            steps {
                script {
                    openshift.withCluster() {
                        openshift.withProject() {
                            echo "Using project: ${openshift.project()}"
                        }
                    }
                }
            }
        }
        stage('More steps') {
	    steps {
		script {
		    openshift.withCluster() {
                        openshift.withProject("vr-poc") {
                            echo "Using project: ${openshift.project()}"
			     def BuildSelector = openshift.selector( 'bc' )
			     BuildSelector.describe()
                        }
              }
	   }
	}
     }	
   }
}
